- name: Learning conditionals concept
  hosts: localhost
  become: yes
  tasks:
    - name: conditionals
      ansible.builtin.command: id expense
      ignore_errors: true
      register: USER # stores the result of id expense output
    - name: conditionals
      ansible.builtin.debug:
        msg: "hello, this after id expense"
    - name: when condition
      ansible.builtin.command: useradd expense
      when: USER.rc !=0 # rc is the exit status of the USER
