- name: Learning conditionals concept
  hosts: localhost
  vars:
    course: AWS DevOps #string
    Tools: #list
    - AWS
    - Terraform
    - ansible
    - docker and k8s
    Experiance: #map or dictionary
      AWS: 2
      Terraform: 2
      Docker: 3
  tasks:
    - name: priting all data types
      ansible.builtin.debug:
        msg: "course: {{course}} and {{Tools}} with {{Experiance}}"