- name: Learning Variable concept
  hosts: localhost
  vars_files:
    - vars.yaml
  # vars: #decalering varuable at play level
  #   WISH: "play"
  # vars_prompt:
  #   - name: WISH
  #     prompt:  "please enter from where you are giving variable"
  #     private: false
  tasks:
    - name: variable decalring
      # vars:
      #   WISH: "task"
      ansible.builtin.debug:
        msg: "hello, this variable from ... {{WISH}}"

# 1. cli/args
# 2. task level
# 3. vars file
# 4. prompt
# 5. play
# 6. inventory
# 7. roles